name: Flutter CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Cloner le projet
        uses: actions/checkout@v3

      - name: Installer Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get

      - run: flutter analyze

      - run: flutter test

      - run: flutter build apk --release
